// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5uZScJH_J87cQFJJeZ5SRSIdH5LQ9nio',
    appId: '1:45022805342:android:f4efd1e3ca0f0b790be3cf',
    messagingSenderId: '45022805342',
    projectId: 'messagingapp-4786c',
    databaseURL: 'https://messagingapp-4786c-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-4786c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAiXbbxDYIBwhNJm10IWLqNoOEMoCz78',
    appId: '1:45022805342:ios:bfbab1fe2828489d0be3cf',
    messagingSenderId: '45022805342',
    projectId: 'messagingapp-4786c',
    databaseURL: 'https://messagingapp-4786c-default-rtdb.firebaseio.com',
    storageBucket: 'messagingapp-4786c.appspot.com',
    androidClientId: '45022805342-3ajea6g4kmcgkq1fdt81483gnrvr473o.apps.googleusercontent.com',
    iosClientId: '45022805342-nr4sgafd4a208o6sgm9dos3ub0a0frfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
